//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLQuanBida.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHDBan
    {
        public int idHD { get; set; }
        public double tongTien { get; set; }
        public System.DateTime NgayXuatHD { get; set; }
        public int idBan { get; set; }
        public int idMH { get; set; }
        public int SoLuong { get; set; }
    
        public virtual Ban Ban { get; set; }
        public virtual MatHang MatHang { get; set; }
        public virtual HDBan HDBan { get; set; }
    }
}
