//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLQuanBida.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMucSPB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanhMucSPB()
        {
            this.SanPhamBans = new HashSet<SanPhamBan>();
        }
    
        public int idDMSPB { get; set; }
        public string TenDMSPB { get; set; }
        public string MaDMSPB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPhamBan> SanPhamBans { get; set; }
    }
}
