//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLQuanBida.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuiCo
    {
        public int idGuiCo { get; set; }
        public string TenMHGui { get; set; }
        public int SoLuong { get; set; }
        public int idKH { get; set; }
        public int idNV { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> Ngaygui { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
