//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLQuanBida.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDBan
    {
        public int idHD { get; set; }
        public double ThanhTien { get; set; }
        public int idNV { get; set; }
        public string MaHD { get; set; }
        public System.DateTime NgayVao { get; set; }
        public System.DateTime NgayRa { get; set; }
        public Nullable<int> idCTKM { get; set; }
        public int idKhachHang { get; set; }
    
        public virtual CTHDBan CTHDBan { get; set; }
        public virtual CTKhuyenMai CTKhuyenMai { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
