//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLQuanBida.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDSPB
    {
        public int idHDSPB { get; set; }
        public string MaHDSPB { get; set; }
        public Nullable<int> idSPB { get; set; }
        public Nullable<int> idNV { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> idKH { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual SanPhamBan SanPhamBan { get; set; }
    }
}
