//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLQuanBida.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MatHang()
        {
            this.CTHDBans = new HashSet<CTHDBan>();
        }
    
        public int IDMH { get; set; }
        public string MaHang { get; set; }
        public string TenHang { get; set; }
        public int IDDVT { get; set; }
        public int IDNhomMH { get; set; }
        public double Gia { get; set; }
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHDBan> CTHDBans { get; set; }
        public virtual DonViTinh DonViTinh { get; set; }
        public virtual NhomMatHang NhomMatHang { get; set; }
    }
}
