//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLQuanBida.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPhamBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPhamBan()
        {
            this.HDSPBs = new HashSet<HDSPB>();
        }
    
        public int idSPB { get; set; }
        public string TenSPB { get; set; }
        public double DonGia { get; set; }
        public string MoTa { get; set; }
        public string MaSPB { get; set; }
        public int idDMSPB { get; set; }
        public int idDVT { get; set; }
    
        public virtual DanhMucSPB DanhMucSPB { get; set; }
        public virtual DonViTinh DonViTinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HDSPB> HDSPBs { get; set; }
    }
}
