//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLQuanBida.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAdmin
    {
        public int id { get; set; }
        public string uSername { get; set; }
        public string pAssWord { get; set; }
        public bool SuDung { get; set; }
        public string tenAdmin { get; set; }
        public string diaChi { get; set; }
        public string sdt { get; set; }
    }
}
